import { AbilityInfo, SectorInfo } from '../types/game';

export const CANVAS_WIDTH = 640;
export const CANVAS_HEIGHT = 360;

export const PLAYER_PHYSICS = {
  WALK_SPEED: 3.2,
  RUN_SPEED: 4.8,
  JUMP_IMPULSE: -7.4,
  FLOAT_IMPULSE: -3.6,
  MAX_FALL_SPEED: 7.0,
  MAX_FLOAT_FALL_SPEED: 1.6,
  GRAVITY: 0.38,
  FLOAT_GRAVITY: 0.14,
  SLIDE_SPEED: 6.2,
  SLIDE_DURATION: 22, // frames
  INVULNERABILITY_FRAMES: 60,
};

export const ABILITIES: Record<string, AbilityInfo> = {
  normal: {
    id: 'normal',
    name: '光靈素體 (Normal)',
    hatColor: '#ffffff',
    hatType: 'none',
    description: '張大嘴巴吸入敵人與物體，可吞嚥吸收能力，或吐出強力貫穿星型彈。',
    puzzleUse: '吐出星型彈觸發遠程機關、吸入雜物。',
    icon: '⭐',
  },
  sword: {
    id: 'sword',
    name: '聖劍使 (Sword)',
    hatColor: '#2ecc71',
    hatType: 'sword_cap',
    description: '揮舞附魔利刃進行三段連斬與空中迴旋斬，斬妖除魔！',
    puzzleUse: '切斷藤蔓、割裂吊繩、水中攻擊。',
    icon: '🗡️',
  },
  fire: {
    id: 'fire',
    name: '烈焰王 (Fire)',
    hatColor: '#e74c3c',
    hatType: 'fire_crown',
    description: '噴射烈火灼燒敵人，或化身火球向前猛烈衝刺爆破！',
    puzzleUse: '點燃炸彈引信、融化厚重冰塊、燒毀枯木藤蔓。',
    icon: '🔥',
  },
  hammer: {
    id: 'hammer',
    name: '重鎚客 (Hammer)',
    hatColor: '#3498db',
    hatType: 'hammer_band',
    description: '掄起沉重巨槌重砸地面，力量驚人，更可蓄力大迴環砸擊！',
    puzzleUse: '將粗大木樁/鐵樁敲入地底開啟暗門，砸碎金屬箱。',
    icon: '🔨',
  },
  spark: {
    id: 'spark',
    name: '雷電霆 (Spark)',
    hatColor: '#f1c40f',
    hatType: 'spark_sparkle',
    description: '周身釋放高壓雷電防護罩，並可發射遠程穿透雷電光束。',
    puzzleUse: '為古代發電機、導電線圈充電以啟動升降梯與機關門。',
    icon: '⚡',
  },
  cutter: {
    id: 'cutter',
    name: '迴旋刃 (Cutter)',
    hatColor: '#f39c12',
    hatType: 'cutter_helmet',
    description: '投擲高速迴旋的月牙飛刃，飛出後會精準繞回手中。',
    puzzleUse: '遠程隔空切斷繩索、回力鏢觸發後方死角開關。',
    icon: '🌙',
  },
};

export const SECTORS: SectorInfo[] = [
  {
    id: 'sec_sanctuary',
    name: '中央神殿',
    subName: 'Prism Sanctuary',
    theme: 'sanctuary',
    primaryColor: '#8e44ad',
    description: '鏡之大迷宮的樞紐，8 面鏡之神門拱衛著失落的萬象稜鏡。',
    shardIndex: -1,
  },
  {
    id: 'sec_grove',
    name: '靜謐綠野',
    subName: 'Emerald Grove',
    theme: 'grove',
    primaryColor: '#27ae60',
    description: '綠意盎然的藤蔓森林，藏有第一塊鏡之碎片。多處藤蔓需以劍刃割斷。',
    shardIndex: 0,
  },
  {
    id: 'sec_forge',
    name: '烈焰深窟',
    subName: 'Crimson Cavern',
    theme: 'forge',
    primaryColor: '#c0392b',
    description: '熔岩沸騰的地下地熱區域，需要火焰能力引爆炸藥開道。',
    shardIndex: 1,
  },
  {
    id: 'sec_frost',
    name: '永凍霜峰',
    subName: 'Frost Peak',
    theme: 'frost',
    primaryColor: '#2980b9',
    description: '狂風呼嘯的極寒冰峰，冰塊封住了前進的暗道與寶箱。',
    shardIndex: 2,
  },
  {
    id: 'sec_ruins',
    name: '雷霆廢墟',
    subName: 'Thunder Spire',
    theme: 'ruins',
    primaryColor: '#d35400',
    description: '失落文明的機械古塔，發電機等待著雷電能量的喚醒。',
    shardIndex: 3,
  },
  {
    id: 'sec_boulder',
    name: '巨石礦坑',
    subName: 'Boulder Quarry',
    theme: 'cavern',
    primaryColor: '#7f8c8d',
    description: '沉重的鋼鐵地樁阻擋前路，重鎚可破除萬難。更有巨石需四人協力！',
    shardIndex: 4,
  },
  {
    id: 'sec_shadow',
    name: '幽影地宮',
    subName: 'Shadow Catacombs',
    theme: 'cavern',
    primaryColor: '#2c3e50',
    description: '幽暗深邃的鏡像迷宮，陷阱與幻影遍佈，考驗光靈的智慧。',
    shardIndex: 5,
  },
  {
    id: 'sec_sky',
    name: '雲端空島',
    subName: 'Sky Sanctum',
    theme: 'storm',
    primaryColor: '#16a085',
    description: '浮空群島之間懸崖深淵，迴旋刃與多段飛行是通過的關鍵。',
    shardIndex: 6,
  },
  {
    id: 'sec_core',
    name: '鏡界核心',
    subName: 'Prism Core',
    theme: 'core',
    primaryColor: '#e056fd',
    description: '最終之所。集齊 8 塊鏡之碎片方能重鑄萬象神鏡，迎戰暗影核心！',
    shardIndex: 7,
  },
];
